Repository wecode-bootcamp-korea/29-westagram-backend-2-team, pull requests merged in 2022-01, with the labels that each got.

#1 Mission 1. [지현] Project Initial Settings
  students/jihyun/.gitignore
  students/jihyun/manage.py
  students/jihyun/westagram/__init__.py
  students/jihyun/westagram/asgi.py
  students/jihyun/westagram/settings.py
  students/jihyun/westagram/urls.py
  students/jihyun/westagram/wsgi.py
Labels: 수정 요청

#4 [지연] Mission 2 모델링
  students/jiyeon/users/models.py
Labels: 멘토 리뷰 요청

#10 Mission 1 : Django 초기 셋팅
  students/hyelin/westargram/.gitignore
  students/hyelin/westargram/manage.py
  students/hyelin/westargram/requirements.txt
  students/hyelin/westargram/westargram/__init__.py
  students/hyelin/westargram/westargram/asgi.py
  students/hyelin/westargram/westargram/settings.py
  students/hyelin/westargram/westargram/urls.py
  students/hyelin/westargram/westargram/wsgi.py
Labels: 멘토 리뷰 요청

#11 [혜린] Mission 2: 모델링
  students/hyelin/westargram/users/__init__.py
  students/hyelin/westargram/users/admin.py
  students/hyelin/westargram/users/apps.py
  students/hyelin/westargram/users/migrations/0001_initial.py
  students/hyelin/westargram/users/migrations/0002_rename_emaail_user_email.py
  students/hyelin/westargram/users/migrations/0003_user_created_at_user_updated_at.py
  students/hyelin/westargram/users/migrations/__init__.py
  students/hyelin/westargram/users/models.py
  students/hyelin/westargram/users/tests.py
  students/hyelin/westargram/users/views.py
  students/hyelin/westargram/westargram/settings.py
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#7 [지연] Misson 3 회원가입 View 기능 정의
  students/jiyeon/users/__init__.py
  students/jiyeon/users/admin.py
  students/jiyeon/users/apps.py
  students/jiyeon/users/migrations/0001_initial.py
  students/jiyeon/users/migrations/__init__.py
  students/jiyeon/users/tests.py
  students/jiyeon/users/views.py
  students/jiyeon/westagram/settings.py
  students/jiyeon/westagram/urls.py
Labels: 멘토 리뷰 요청

#12 [지연] Mission 4: 로그인 기능 구현
  students/jiyeon/users/views.py
  students/jiyeon/westagram/urls.py
Labels: 피어 리뷰 요청

#16 [혜린] Mission 4: 로그인 기능 구현
  students/hyelin/westargram/requirements.txt
  students/hyelin/westargram/users/models.py
  students/hyelin/westargram/users/urls.py
  students/hyelin/westargram/users/views.py
  students/hyelin/westargram/westargram/settings.py
  students/hyelin/westargram/westargram/urls.py
Labels: 멘토 리뷰 요청, 피어 리뷰 요청
